name: Build (Linux/Windows/Mac)

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            shell: pwsh
            name: Build for Windows
            BUILD_NAME: SaucisseTracker_Windows
            BUILD_ARGS: -F -w --add-data "res;res" -i "res/icon.png" src/main.py
            CMD_EXEC: PyInstaller
            FILE_TYPE: ".exe"
            LIB_EXTENSION: dll
            CMD_ZIP: New-Item -Path "dist/lib" -ItemType Directory; New-Item -Path "output" -ItemType Directory; Copy-Item "lib/*.dll" -Destination "dist/lib/"; cd /D ./dist/; Compress-Archive -Path "." -DestinationPath "../output/SaucisseTracker_Windows.zip"

          - os: ubuntu-latest
            shell: bash
            name: Build for Linux
            BUILD_NAME: SaucisseTracker_Linux
            BUILD_ARGS: -F -w --add-data "res:res" src/main.py
            CMD_EXEC: pyinstaller
            FILE_TYPE: ""
            LIB_EXTENSION: so
            CMD_ZIP: mkdir -p dist/lib/ output && cp -v lib/*.so dist/lib/ && cd dist && zip -r ../output/SaucisseTracker_Linux.zip .

    name: "${{ matrix.name }}"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Project for ${{ matrix.os }}
        run: ${{ matrix.CMD_EXEC }} ${{ matrix.BUILD_ARGS }} -n ${{ matrix.BUILD_NAME }}

      - name: Create Archive
        run: ${{ matrix.CMD_ZIP }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.BUILD_NAME }}
          path: output/SaucisseTracker.zip

      - name: Upload main rolling release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: 'Rolling release'
          body: Release built from latest commit on `main` branch. Check the commit history for more details.
          target_commitish: main
          tag_name: 'rolling_pre-release'
          prerelease: true
          files: output/${{ matrix.BUILD_NAME }}.zip
        continue-on-error: true

      - name: Upload dev rolling pre-release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/dev'
        with:
          name: 'Rolling pre-release'
          body: Experimental pre-release built from latest commit on `dev` branch. Check the commit history for more details.
          target_commitish: dev
          tag_name: 'rolling_pre-release'
          prerelease: true
          files: output/${{ matrix.BUILD_NAME }}.zip
        continue-on-error: true
